apiVersion: v1
kind: Service
metadata:
  name: travelmemory-be-service
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30070

