apiVersion: v1
kind: Service
metadata:
  name: travelmemory-fe-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000

