apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelmemory-be-deployment
  labels:
    apps: nodejs 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: travelmemory-be
          image: amolkhetan/backend-tm:v1.0
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              valueFrom:
                 configMapKeyRef:
                  name: travelmemory-be-config
                  key: MONGO_URI
            
