apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelmemory-fe-deployment
  labels:
    apps: nodejs 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: travelmemory-fe
          image: amolkhetan/frontend-tm:v1.0
          ports:
            - containerPort: 3000
